/*global define */

define(function (require) {
  'use strict';

  return {
    Accordion: require('./lib/Accordion'),
    Affix: require('./lib/Affix'),
    AffixMixin: require('./lib/AffixMixin'),
    Alert: require('./lib/Alert'),
    BootstrapMixin: require('./lib/BootstrapMixin'),
    Badge: require('./lib/Badge'),
    Button: require('./lib/Button'),
    ButtonGroup: require('./lib/ButtonGroup'),
    ButtonToolbar: require('./lib/ButtonToolbar'),
    Carousel: require('./lib/Carousel'),
    CarouselItem: require('./lib/CarouselItem'),
    Col: require('./lib/Col'),
    CollapsableMixin: require('./lib/CollapsableMixin'),
    DropdownButton: require('./lib/DropdownButton'),
    DropdownMenu: require('./lib/DropdownMenu'),
    DropdownStateMixin: require('./lib/DropdownStateMixin'),
    FadeMixin: require('./lib/FadeMixin'),
    Glyphicon: require('./lib/Glyphicon'),
    Grid: require('./lib/Grid'),
    Input: require('./lib/Input'),
    Interpolate: require('./lib/Interpolate'),
    Jumbotron: require('./lib/Jumbotron'),
    Label: require('./lib/Label'),
    ListGroup: require('./lib/ListGroup'),
    ListGroupItem: require('./lib/ListGroupItem'),
    MenuItem: require('./lib/MenuItem'),
    Modal: require('./lib/Modal'),
    Nav: require('./lib/Nav'),
    Navbar: require('./lib/Navbar'),
    NavItem: require('./lib/NavItem'),
    ModalTrigger: require('./lib/ModalTrigger'),
    OverlayTrigger: require('./lib/OverlayTrigger'),
    OverlayMixin: require('./lib/OverlayMixin'),
    PageHeader: require('./lib/PageHeader'),
    Panel: require('./lib/Panel'),
    PanelGroup: require('./lib/PanelGroup'),
    PageItem: require('./lib/PageItem'),
    Pager: require('./lib/Pager'),
    Popover: require('./lib/Popover'),
    ProgressBar: require('./lib/ProgressBar'),
    Row: require('./lib/Row'),
    SplitButton: require('./lib/SplitButton'),
    SubNav: require('./lib/SubNav'),
    TabbedArea: require('./lib/TabbedArea'),
    Table: require('./lib/Table'),
    TabPane: require('./lib/TabPane'),
    Tooltip: require('./lib/Tooltip'),
    Well: require('./lib/Well')
  };
});
