#!/usr/bin/env node
/* eslint no-var: 0 */
require('babel/register');
var path = require('path');
var nodeModulesBin = path.resolve(__dirname, '../node_modules/.bin');
process.env.PATH = nodeModulesBin + ':' + process.env.PATH;
require('./release-scripts/release');

